name: branches

on:
  push:
    branches: [ !master ]
  pull_request:
    branches: [ !master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        FIRE: ${{ secrets.FIRE }}
      run: |
        lein cloverage
